api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
 #   patch_formats:
  #      multipart: ['multipart/form-data']
  #      json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        force_eager: false
    collection:
        order_parameter_name: '_order'
    